// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwlu79alK2P3_44BWNvOnne6aTiasyVg',
    appId: '1:972211348634:web:28e50d3ba6af450b88eb23',
    messagingSenderId: '972211348634',
    projectId: 'kirana-store-app-f88b9',
    authDomain: 'kirana-store-app-f88b9.firebaseapp.com',
    storageBucket: 'kirana-store-app-f88b9.appspot.com',
    measurementId: 'G-LPHX3NPGSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyWsh9O26qn4SmEeM_jDIF1W55zyPWYo',
    appId: '1:972211348634:android:4ff641b5a63ff79188eb23',
    messagingSenderId: '972211348634',
    projectId: 'kirana-store-app-f88b9',
    storageBucket: 'kirana-store-app-f88b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5g4CJAGutDMGX6_pYn-jRMHoMp0Kcgk',
    appId: '1:972211348634:ios:d964569c3697898188eb23',
    messagingSenderId: '972211348634',
    projectId: 'kirana-store-app-f88b9',
    storageBucket: 'kirana-store-app-f88b9.appspot.com',
    androidClientId: '972211348634-9dre7u3h1b38slrnfu2f5agq144hrt53.apps.googleusercontent.com',
    iosClientId: '972211348634-283pqcg78iehc18fkug0c1b3vhe8k622.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiranaStoreCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5g4CJAGutDMGX6_pYn-jRMHoMp0Kcgk',
    appId: '1:972211348634:ios:54cb7e7f468b704788eb23',
    messagingSenderId: '972211348634',
    projectId: 'kirana-store-app-f88b9',
    storageBucket: 'kirana-store-app-f88b9.appspot.com',
    androidClientId: '972211348634-9dre7u3h1b38slrnfu2f5agq144hrt53.apps.googleusercontent.com',
    iosClientId: '972211348634-vsgm9c1ttcogi8df5lm7bva5p4a3lmpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiranaStoreCrm.RunnerTests',
  );
}
